swagger: '2.0'
info:
  description: API to manage users and trails.
  version: "1.0.0"
  title: TrailService API
paths:
  /users:
    post:
      summary: Add a new user
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: User object to add
          schema:
            type: object
            required:
              - UserName
            properties:
              UserName:
                type: string
      responses:
        201:
          description: User added successfully
        400:
          description: Bad request
        500:
          description: Internal server error
    get:
      summary: Retrieve all users
      description: Returns a list of all users in the database.
      responses:
        200:
          description: A list of users in the database
          schema:
            type: array
            items:
              type: object
              properties:
                ID:
                  type: integer
                  description: The user ID
                Name:
                  type: string
                  description: The user name
        500:
          description: Internal server error
